export const keterisianDataPemanfaatan = {
  1: {
    name: 'Direktorat Rumah Susun',
    fields: [
      'ProKegiatan.nama',
      'ProSatker.nama',
      'Provinsi.nama',
      'City.nama',
      'Kecamatan.nama',
      'Desa.nama',
      'ProSatker.ProBalai.nama',
      'ProSatker.id_balai',
      'id_kegiatan',
      'id_satker',
      'id_provinsi',
      'id_kabkota',
      'id_kecamatan',
      'id_keldesa',
      'alamat',
      'longitude',
      'latitude',
      'tgt_hunian',
      'jml_unit',
      'tipe_unit',
      'tower',
      'jml_lantai',
      'nm_kontraktor',
      'nm_perumahan',
      'jml_unit_huni',
      'stat_srh_trm',
      'thn_serah_aset',
      'tot_biaya',
      'thn_bang',
    ],
  },
  2: {
    name: 'Direktorat Rumah Khusus',
    fields: [
      'id_kegiatan',
      'ProKegiatan.nama',
      'id_satker',
      'ProSatker.nama',
      'id_provinsi',
      'Provinsi.nama',
      'id_kabkota',
      'City.nama',
      'id_kecamatan',
      'Kecamatan.nama',
      'id_keldesa',
      'Desa.nama',
      'alamat',
      'longitude',
      'latitude',
      'tgt_hunian',
      'jml_unit',
      'tipe_unit',
      'nm_perumahan',
      'sumb_dana',
      'jml_unit_huni',
      'stat_srh_trm',
      'thn_serah_aset',
      'tot_biaya',
      'ProSatker.ProBalai.nama',
      'ProSatker.id_balai',
      'thn_bang',
      'nm_perumahan',
    ],
  },
  3: {
    name: 'Direktorat Rumah Swadaya',
    fields: [],
  },
  4: {
    name: 'Direktorat Rumah Umum dan Komersil',
    fields: [
      'id_kegiatan',
      'ProKegiatan.nama',
      'id_satker',
      'ProSatker.nama',
      'id_provinsi',
      'Provinsi.nama',
      'id_kabkota',
      'City.nama',
      'id_kecamatan',
      'Kecamatan.nama',
      'id_keldesa',
      'Desa.nama',
      'alamat',
      'longitude',
      'latitude',
      'jml_unit',
      'tipe_unit',
      'nm_pengembang',
      'nm_perumahan',
      'tot_biaya',
      'ProSatker.ProBalai.nama',
      'ProSatker.id_balai',
      'thn_bang',
    ],
  },
}
